export const HOLAPLEX_MARKETPLACE_SUBDOMAIN = `haus`;

export const HOLAPLEX_MARKETPLACE_ADDRESS = `9SvsTjqk3YoicaYnC4VW1f8QAN9ku7QCCk6AyfUdzc9t`;

export const OPENSEA_MARKETPLACE_ADDRESS = '3o9d13qUvEuuauhFrVom1vuCzgNsJifeaBYDPquaT73Y';

export const HOLAPLEX_MONITORING_PUBLIC_KEY = 'BpVYWaAPbv5vyeRxiX9PMsmAVJVoL2Lp4YtuRgjuhoZh';
